apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: cfe-build
  name: cfe-build
  namespace: cfe
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'cfe:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker