kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "cfe-pipeline"
spec:
  source:
    git:
      ref: main
      uri: 'https://github.com/Maxis-System-Limited/maxis-collection-portal-frontend.git'
    sourceSecret:
      name: cfe-secret
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/jenkinsFile
    type: JenkinsPipeline